### ISSUE TITLE
Use wasilibs as in coraza-proxy-wasm

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/coraza-http-wasm#5]

**Comment by M4tteoP** [comment]
Wasilibs operators have been added via https://github.com/jcchavezs/coraza-http-wasm/pull/7, see the registration here: https://github.com/jcchavezs/coraza-http-wasm/blob/d48f46ff8e3926447acb5e3c29bb3380d682da79/main.go#L22-L25
